name:                paradigmardos
version:             0.1.0.0

extra-source-files:
- README.md
- INSTALL.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- gloss >= 1.13

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  paradigmardos-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paradigmardos